site_name: ckanext-files
site_url: https://datashades.github.io/ckanext-files/
repo_url:  https://github.com/DataShades/ckanext-files

markdown_extensions:
    - pymdownx.snippets
    - admonition
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
            alternate_style: true

plugins:
    - search:
        separator: '[\s\-\.\_]+'
    - mkdocstrings:
        handlers:
          python:
            paths: ["ckanext"]
            options:
              show_root_full_path: false
              show_root_heading: true
              # show_root_toc_entry: true
              show_symbol_type_heading: true
              show_source: false
              docstring_section_style: spacy

watch:
  - README.md
  - ckanext/files

theme:
    name: material
    logo: img/logo.png
    favicon: img/favicon.ico
    palette:
      # Palette toggle for light mode
      # Palette toggle for automatic mode
      - media: "(prefers-color-scheme)"
        toggle:
          icon: material/brightness-auto
          name: Switch to light mode

      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: blue
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode

      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to system preference
    features:
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.instant.progress
        - navigation.top
        - navigation.footer
        - navigation.indexes
        - content.code.copy
        - content.code.select
        - content.code.annotate

nav:
    - index.md
    - installation.md
    - Usage:
        - usage/configure.md
        - usage/use-in-code.md
        - usage/use-in-browser.md
        - usage/multi-storage.md
        - usage/tracked-files.md
        - usage/permissions.md
        - usage/ownership.md
        - usage/transfer.md
        - usage/task-queue.md
        - usage/capabilities.md
        - usage/multipart.md
        - usage/js.md

    - upload-strategies.md
    - implementation-example.md
    - Shared:
            - shared/index.md
            - shared/types.md
            - shared/config.md
            - shared/exceptions.md
    - cli.md
    - API: api.md
    - validators.md
    - interfaces.md
    - Configuration:
        - configuration/index.md
        - configuration/global.md
        - Storage configuration:
            - configuration/storage/index.md
            - configuration/redis.md
            - configuration/fs.md
            - configuration/opendal.md
            - configuration/libcloud.md
    - Migration(experimental):
        - migration/index.md
        - migration/group.md
        - migration/user.md
        - migration/resource.md

    - changelog.md
