name: Frontend tests
env:
  NODE_VERSION: '20'
  PYTHON_VERSION: '3.9'

permissions:
  contents: read

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    services:
      ckan-postgres:
        image: postgres:10
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: ckan_default
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: ckan_test

      ckan-redis:
        image: redis
        ports:
          - 6379:6379
      ckan-solr:
        image: ckan/ckan-solr:master
        ports:
          - 8983:8983

    env:
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@localhost/ckan_test
      CKAN_SOLR_URL: http://localhost:8983/solr/ckan
      CKAN_REDIS_URL: redis://localhost:6379/1

    steps:
      - uses: actions/checkout@v3
      - name: Install Cypress deps
        run: |
            apt update
            apt install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install python deps
        run: |
            git clone --depth 1 --branch ckan-2.10.4 https://github.com/ckan/ckan ../ckan
            pip install '../ckan[requirements,dev]' -e.

      - name: Init environment
        run: |
          ckan -c test.ini db upgrade

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          start: ckan -c test.ini run

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
